### PR TITLE
fix TOC issues

### PR DESCRIPTION
**Pull request by mairaw**
@nokura while verifying fix for the TOC issue, I've noticed there were some issues with the TOC for Spanish. They might exist for other languages too.

### CODE REVIEW

**Comment by mairaw** [comment]
@nokura @gosali should someone review this?

**Comment by nokura** [comment]
Sorry for the delay. We are working on it an will resolve soon.

**Comment by gosali** [comment]
@nokura   We are checking this with the Production team.

@mairaw Do you have a the website where this TOC is incorrectly showed?
In GitHUb it shows correctly: https://github.com/dotnet/docs.es-es/blob/2b0d45ada9d8931526afbe1d21376a7261aecf7d/docs/toc.md

Thanks you in advance.

**Comment by v-radelg** [comment]
@mairaw , Thank you for your feedback and suggestion! 

The suggestion will be merged to the production, we will re-release this articles in the next loc release round.

Microsoft C&E Localization Team

**Pull request merged**
